#!/bin/bash

colourf="\033[34;40m"
none="\033[0m"
day=$(date)
System_Info="output.txt"
echo -e $colourf "SYSTEM INFORMATION AS AT $day." $none

echo " *****CPU INFO****"
cpuinfo=$(lscpu | head -n 5)
echo "$cpuinfo" >> "$System_Info"
echo "$cpuinfo"

echo "*****HARDWARE DEVICES******"
harddevices=$(lshw | grep -i "core" "memory")
echo "$harddevices" >> "$System_Info"
echo "$harddevices"

echo "******BASIC CPU ARCHITECTURE*****"
arch=$(uname -a)
echo "$arch" >> "$System_Info"
echo "$arch"

echo "*****DISK SPACE*****"
disk=$(df -h)
echo "$disk" >> "$System_Info"
echo "$disk"

echo "*****MEMORY STATUS*****"
mem=$(free -h)
echo "$mem" >> "$System_Info"
echo "$mem"

printf "Bash Version: %s\n" $BASH_VERSION
echo "$BASH_VERSION" >> "$System_Info"

cat << EOF >> $System_Info
	This report was automatically generated by my Bash Script.
EOF
