#!/bin/bash

color="\033[36;40m"
none="\033[0m"
day=$(date)
logfile="output1.txt"

echo -e $color "SYSTEM INFOMATION AS AT $day"$none

machtype=$(MACHTYPE)
hostname=$(HOSTNAME)
bash=$(BASH_VERSION)
disk=$(df -h | grep -E "\/$" | awk '{print $4}')

printf "Free disk space:%s\n" $disk
printf "The machtype is :%s\n" $machtype
printf "Hostname: %s\n" $hostname
printf "Bash version: %s\n" $bash

cat << EOF >> $logfile
	This report was automatically generated by my Bash Script.
	It contains a brief summary of some system information
EOF
echo "$machtype" "$hostname" "$bash" "$disk" >> "$logfile" 
